In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.read_csv?

In [2]:
df=pd.read_csv("framingham.csv")
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  POSSIBILITY OF CVD  
0          80.0     77.0                   0  
1          95.0     76.0                   0  
2          75.0     70.0                   0  
3          65.0    103.0                   1  
4          85.0     85.0                   0  
...         ...      ...                 ...  
4233       66.0     86.0                   1  
4234       65.0     68.0                   0  
4235       84.0     86.0                   0  
4236       86.0      NaN                   0  
4237       80.0    107.0                   0  

[4238 rows x 16 columns]

In [3]:
# "education" showed -ve correlation, with target label
# "male" was shown to be IN SIGNIFICANT, during T TEst(based on p-value)
# "diabetes" was shown to be IN SIGNIFICANT, during T TEst(based on p-value)
# "currentSmoker" fails in chi-square test
df=df.drop(axis=1,labels=["male","education","diabetes","currentSmoker"])
df

age  cigsPerDay  BPMeds  prevalentStroke  prevalentHyp  totChol  sysBP  \
0      39         0.0     0.0                0             0    195.0  106.0   
1      46         0.0     0.0                0             0    250.0  121.0   
2      48        20.0     0.0                0             0    245.0  127.5   
3      61        30.0     0.0                0             1    225.0  150.0   
4      46        23.0     0.0                0             0    285.0  130.0   
...   ...         ...     ...              ...           ...      ...    ...   
4233   50         1.0     0.0                0             1    313.0  179.0   
4234   51        43.0     0.0                0             0    207.0  126.5   
4235   48        20.0     NaN                0             0    248.0  131.0   
4236   44        15.0     0.0                0             0    210.0  126.5   
4237   52         0.0     0.0                0             0    269.0  133.5   

      diaBP    BMI  heartRate  glucose  POSSIBILITY OF CVD  
0      70.0  26.97       80.0     77.0                   0  
1      81.0  28.73       95.0     76.0                   0  
2      80.0  25.34       75.0     70.0                   0  
3      95.0  28.58       65.0    103.0                   1  
4      84.0  23.10       85.0     85.0                   0  
...     ...    ...        ...      ...                 ...  
4233   92.0  25.97       66.0     86.0                   1  
4234   80.0  19.71       65.0     68.0                   0  
4235   72.0  22.00       84.0     86.0                   0  
4236   87.0  19.16       86.0      NaN                   0  
4237   83.0  21.47       80.0    107.0                   0  

[4238 rows x 12 columns]

## Preprocessing data

In [4]:
#To understand , which attribute has how many ("NULL" or NaN) values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 4238 non-null   int64  
 1   cigsPerDay          4209 non-null   float64
 2   BPMeds              4185 non-null   float64
 3   prevalentStroke     4238 non-null   int64  
 4   prevalentHyp        4238 non-null   int64  
 5   totChol             4188 non-null   float64
 6   sysBP               4238 non-null   float64
 7   diaBP               4238 non-null   float64
 8   BMI                 4219 non-null   float64
 9   heartRate           4237 non-null   float64
 10  glucose             3850 non-null   float64
 11  POSSIBILITY OF CVD  4238 non-null   int64  
dtypes: float64(8), int64(4)
memory usage: 397.4 KB


In [5]:
# each column has 4238 entries.
# for attribute "glucose" , there are only 3850 "not-NULL" entries
#df.fillna?

In [6]:
# for categorical attributes, we replace Nan with most frequent attribute
#for continous attributes,we replace Nan with mean .

#for continous attributes--->replace Nan with mean
df["cigsPerDay"]=df["cigsPerDay"].fillna(round(df["cigsPerDay"].mean()))
df["totChol"]=df["totChol"].fillna(round(df["totChol"].mean()))
df["BMI"]=df["BMI"].fillna(round(df["BMI"].mean(),2))
df["heartRate"]=df["heartRate"].fillna(round(df["heartRate"].mean()))
df["glucose"]=df["glucose"].fillna(round(df["glucose"].mean()))


#for categorical attributes-->replace Nan with most freq value
vall,freqq=np.unique(df["BPMeds"],return_counts=True)
#display(vall,freqq)
df["BPMeds"]=df["BPMeds"].fillna(vall[freqq.argmax()])

display(df)

age  cigsPerDay  BPMeds  prevalentStroke  prevalentHyp  totChol  sysBP  \
0      39         0.0     0.0                0             0    195.0  106.0   
1      46         0.0     0.0                0             0    250.0  121.0   
2      48        20.0     0.0                0             0    245.0  127.5   
3      61        30.0     0.0                0             1    225.0  150.0   
4      46        23.0     0.0                0             0    285.0  130.0   
...   ...         ...     ...              ...           ...      ...    ...   
4233   50         1.0     0.0                0             1    313.0  179.0   
4234   51        43.0     0.0                0             0    207.0  126.5   
4235   48        20.0     0.0                0             0    248.0  131.0   
4236   44        15.0     0.0                0             0    210.0  126.5   
4237   52         0.0     0.0                0             0    269.0  133.5   

      diaBP    BMI  heartRate  glucose  POSSIBILITY OF CVD  
0      70.0  26.97       80.0     77.0                   0  
1      81.0  28.73       95.0     76.0                   0  
2      80.0  25.34       75.0     70.0                   0  
3      95.0  28.58       65.0    103.0                   1  
4      84.0  23.10       85.0     85.0                   0  
...     ...    ...        ...      ...                 ...  
4233   92.0  25.97       66.0     86.0                   1  
4234   80.0  19.71       65.0     68.0                   0  
4235   72.0  22.00       84.0     86.0                   0  
4236   87.0  19.16       86.0     82.0                   0  
4237   83.0  21.47       80.0    107.0                   0  

[4238 rows x 12 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 4238 non-null   int64  
 1   cigsPerDay          4238 non-null   float64
 2   BPMeds              4238 non-null   float64
 3   prevalentStroke     4238 non-null   int64  
 4   prevalentHyp        4238 non-null   int64  
 5   totChol             4238 non-null   float64
 6   sysBP               4238 non-null   float64
 7   diaBP               4238 non-null   float64
 8   BMI                 4238 non-null   float64
 9   heartRate           4238 non-null   float64
 10  glucose             4238 non-null   float64
 11  POSSIBILITY OF CVD  4238 non-null   int64  
dtypes: float64(8), int64(4)
memory usage: 397.4 KB


# KNN Implementation

### Step 0: preparing data

In [8]:
# random shuffling of data
#df=df.sample(frac=1)
#display(df)

#not doing this step, as data is already shuffled, as per dataset discription

In [9]:
# taking data , from the DataFrame object, to numpy object
data=df.values
print(data)
print(data.shape)
print(type(data))

[[ 39.   0.   0. ...  80.  77.   0.]
 [ 46.   0.   0. ...  95.  76.   0.]
 [ 48.  20.   0. ...  75.  70.   0.]
 ...
 [ 48.  20.   0. ...  84.  86.   0.]
 [ 44.  15.   0. ...  86.  82.   0.]
 [ 52.   0.   0. ...  80. 107.   0.]]
(4238, 12)
<class 'numpy.ndarray'>


In [10]:
#separating target label, from rest of the attributes
X=data[:,:-1]  
Y=data[:,-1]  # target label
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 39.     0.     0.   ...  26.97  80.    77.  ]
 [ 46.     0.     0.   ...  28.73  95.    76.  ]
 [ 48.    20.     0.   ...  25.34  75.    70.  ]
 ...
 [ 48.    20.     0.   ...  22.    84.    86.  ]
 [ 44.    15.     0.   ...  19.16  86.    82.  ]
 [ 52.     0.     0.   ...  21.47  80.   107.  ]]
(4238, 11)
[0. 0. 0. ... 0. 0. 0.]
(4238,)


### step1 : splitting data for training and testing

In [11]:
#performing split , to train,test data
split=0.7*X.shape[0]
print(split)
split=int(split)
print("split length:",split)
print()

X_train= X[:split,:]
Y_train=Y[:split]
X_test=X[split:,:]
Y_test=Y[split:]

print("X_train:",X_train.shape)
print("X_test:",X_test.shape)
print("Y_train:",Y_train.shape)
print("Y_test:",Y_test.shape)

2966.6
split length: 2966

X_train: (2966, 11)
X_test: (1272, 11)
Y_train: (2966,)
Y_test: (1272,)


### Step 2: knn implementation (k=5)

In [15]:
#function to calculaate eucledian distance
def EucledianDist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

In [16]:
# A EXAMPLE
# defining 2 points,  in 4 dimension space
a=np.array([3,3,3,3])
b=np.array([1,1,1,1])
# calculating the eucledian distance , between these 2 points
EucledianDist(a,b) 
# ie sqrt(4+4+4+4)=4

4.0

In [17]:
def knn(queryPoint,printIntermidiateResults=False,k=5):
    values=[]  #to store dist of query point, with each of training points,with label
    m=X_train.shape[0]  # ie m=2559
    
    for i in range(m):
        d=EucledianDist(queryPoint,X_train[i])
        values.append((d,Y_train[i]))
        
    #print(values)
    values.sort(key=lambda z:z[0])  #sort in ascending order of eucledian dist
    #print(values)
    values=values[:k]  # K nearest neighbour
    if(printIntermidiateResults):
        print("k nearest points, along with their label:\n",values)
    values=np.array(values) #converting to np array, to do slicing property 
    
    #count the frequency of each of the unique labels
    new_values=np.unique(values[:,1],return_counts=True) 
    if(printIntermidiateResults):
        print("\nunique labels, their frequency:\n",new_values)
    indexOf_MostFreqLabel=new_values[1].argmax()
    
    prediction=new_values[0][indexOf_MostFreqLabel]
    if(printIntermidiateResults):
        print("\npredicted label=",prediction)
    return prediction
    
    
    
        

#### understanding how it works, on 1 sample point

In [40]:

knn(X_test[15],True)

k nearest points, along with their label:
 [(18.022988098536825, 0.0), (18.12186800525818, 0.0), (18.95069655711895, 1.0), (19.418805318556544, 1.0), (20.7176277599536, 1.0)]

unique labels, their frequency:
 (array([0., 1.]), array([2, 3]))

predicted label= 1.0


1.0

In [41]:
#compare above result of KNN, with the actual Label
print(Y_test[:20])
print("actual Label=",Y_test[15])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
actual Label= 1.0


### Step 3: Testing with "Testing Set"

In [20]:
def TestKNN(k_parameter=5):
    m=X_test.shape[0] # m=1097
    print("number of test cases:",m)

    val=[]
    correctPrediction=0
    wrongPrediction=0
    for i in range(m):
        modelPrediction=knn(X_test[i],k=k_parameter)
        l=[modelPrediction,Y_test[i]]
        val.append(l)
        if(modelPrediction!=Y_test[i]):
            wrongPrediction+=1
        else:
            correctPrediction+=1
    df1=pd.DataFrame(data=val,columns=["Label predicted by KNN","Actual Label"])

    print("\n% of correct Prediction:",correctPrediction*100/m)
    print("% of wrong Prediction:",wrongPrediction*100/m)
    display(df1)
    



In [21]:
TestKNN(k_parameter=5)

number of test cases: 1272

% of correct Prediction: 83.01886792452831
% of wrong Prediction: 16.9811320754717


Label predicted by KNN  Actual Label
0                        0.0           0.0
1                        0.0           0.0
2                        0.0           0.0
3                        0.0           0.0
4                        0.0           0.0
...                      ...           ...
1267                     0.0           1.0
1268                     0.0           0.0
1269                     0.0           0.0
1270                     0.0           0.0
1271                     0.0           0.0

[1272 rows x 2 columns]

In [69]:
TestKNN(k_parameter=15)

number of test cases: 1097

% of correct Prediction: 84.68550592525068
% of wrong Prediction: 15.314494074749316


Label predicted by KNN  Actual Label
0                        0.0           0.0
1                        0.0           0.0
2                        0.0           1.0
3                        0.0           0.0
4                        0.0           0.0
...                      ...           ...
1092                     0.0           0.0
1093                     1.0           1.0
1094                     0.0           1.0
1095                     0.0           0.0
1096                     0.0           0.0

[1097 rows x 2 columns]

In [70]:
TestKNN(k_parameter=95)
# most of the Predicted Labels are 0, 
#not at all helpful, to predict cvd

number of test cases: 1097

% of correct Prediction: 84.86782133090246
% of wrong Prediction: 15.132178669097538


Label predicted by KNN  Actual Label
0                        0.0           0.0
1                        0.0           0.0
2                        0.0           1.0
3                        0.0           0.0
4                        0.0           0.0
...                      ...           ...
1092                     0.0           0.0
1093                     0.0           1.0
1094                     0.0           1.0
1095                     0.0           0.0
1096                     0.0           0.0

[1097 rows x 2 columns]

# Implementing KNN with sk-learn

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knc = KNeighborsClassifier(n_neighbors = 15)

In [14]:
knc.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=15)

In [15]:
knc.score(X_train,Y_train)

0.851652056641942

In [16]:
knc.score(X_test,Y_test)

0.8490566037735849

# Evaluating Performance , by Evaluating Parameters

In [27]:
Y_pred=knc.predict(X_test)

In [28]:
def evaluateParameters(Y_pred,Y_test):
    tp,tn,fp,fn=0,0,0,0
    for i in range(len(Y_test)):
        actual=Y_test[i]
        if(actual==1):
            if(actual==Y_pred[i]):
                tp+=1
            else:
                fn+=1
        else:
            if(actual==Y_pred[i]):
                tn+=1
            else:
                fp+=1
    print("\naccuracy= ",(tp+tn)/(tp+tn+fn+fp))
    print("\nsensitivity= ",tp/(tp+fn))
    print("\nspecificity= ",tn/(fp+tn))
    print("\nPPv= ",tp/(tp+fp))
    print("\nNPV= ",tn/(tn+fn))
    
            
            

In [29]:
evaluateParameters(Y_pred,Y_test)


accuracy=  0.8490566037735849

sensitivity=  0.047619047619047616

specificity=  0.9889196675900277

PPv=  0.42857142857142855

NPV=  0.8561151079136691


# save the trained model, for deploying on web

In [17]:

import pickle

In [18]:
with open('knn_model.pkl','wb') as f:
    pickle.dump(knc,f)