In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("framingham.csv")
display(df)

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  POSSIBILITY OF CVD  
0          80.0     77.0                   0  
1          95.0     76.0                   0  
2          75.0     70.0                   0  
3          65.0    103.0                   1  
4          85.0     85.0                   0  
...         ...      ...                 ...  
4233       66.0     86.0                   1  
4234       65.0     68.0                   0  
4235       84.0     86.0                   0  
4236       86.0      NaN                   0  
4237       80.0    107.0                   0  

[4238 rows x 16 columns]

## Preprocessing data

In [3]:
# "male" was shown to be IN SIGNIFICANT, during T TEst(based on p-value)
# "diabetes" was shown to be IN SIGNIFICANT, during T TEst(based on p-value)
# "currentSmoker" fails in chi-square test
df=df.drop(axis=1,labels=["male","education","diabetes","currentSmoker"])
df


age  cigsPerDay  BPMeds  prevalentStroke  prevalentHyp  totChol  sysBP  \
0      39         0.0     0.0                0             0    195.0  106.0   
1      46         0.0     0.0                0             0    250.0  121.0   
2      48        20.0     0.0                0             0    245.0  127.5   
3      61        30.0     0.0                0             1    225.0  150.0   
4      46        23.0     0.0                0             0    285.0  130.0   
...   ...         ...     ...              ...           ...      ...    ...   
4233   50         1.0     0.0                0             1    313.0  179.0   
4234   51        43.0     0.0                0             0    207.0  126.5   
4235   48        20.0     NaN                0             0    248.0  131.0   
4236   44        15.0     0.0                0             0    210.0  126.5   
4237   52         0.0     0.0                0             0    269.0  133.5   

      diaBP    BMI  heartRate  glucose  POSSIBILITY OF CVD  
0      70.0  26.97       80.0     77.0                   0  
1      81.0  28.73       95.0     76.0                   0  
2      80.0  25.34       75.0     70.0                   0  
3      95.0  28.58       65.0    103.0                   1  
4      84.0  23.10       85.0     85.0                   0  
...     ...    ...        ...      ...                 ...  
4233   92.0  25.97       66.0     86.0                   1  
4234   80.0  19.71       65.0     68.0                   0  
4235   72.0  22.00       84.0     86.0                   0  
4236   87.0  19.16       86.0      NaN                   0  
4237   83.0  21.47       80.0    107.0                   0  

[4238 rows x 12 columns]

In [4]:
#To understand , which attribute has how many ("NULL" or NaN) values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 4238 non-null   int64  
 1   cigsPerDay          4209 non-null   float64
 2   BPMeds              4185 non-null   float64
 3   prevalentStroke     4238 non-null   int64  
 4   prevalentHyp        4238 non-null   int64  
 5   totChol             4188 non-null   float64
 6   sysBP               4238 non-null   float64
 7   diaBP               4238 non-null   float64
 8   BMI                 4219 non-null   float64
 9   heartRate           4237 non-null   float64
 10  glucose             3850 non-null   float64
 11  POSSIBILITY OF CVD  4238 non-null   int64  
dtypes: float64(8), int64(4)
memory usage: 397.4 KB


In [5]:
# each column has 4238 entries.
# for attribute "glucose" , there are only 3850 "not-NULL" entries
#df.fillna?

In [6]:
# for categorical attributes, we replace Nan with most frequent attribute
#for continous attributes,we replace Nan with mean .

#for continous attributes--->replace Nan with mean
df["cigsPerDay"]=df["cigsPerDay"].fillna(round(df["cigsPerDay"].mean()))
df["totChol"]=df["totChol"].fillna(round(df["totChol"].mean()))
df["BMI"]=df["BMI"].fillna(round(df["BMI"].mean(),2))
df["heartRate"]=df["heartRate"].fillna(round(df["heartRate"].mean()))
df["glucose"]=df["glucose"].fillna(round(df["glucose"].mean()))


#for categorical attributes-->replace Nan with most freq value
vall,freqq=np.unique(df["BPMeds"],return_counts=True)
#display(vall,freqq)
df["BPMeds"]=df["BPMeds"].fillna(vall[freqq.argmax()])

display(df)

age  cigsPerDay  BPMeds  prevalentStroke  prevalentHyp  totChol  sysBP  \
0      39         0.0     0.0                0             0    195.0  106.0   
1      46         0.0     0.0                0             0    250.0  121.0   
2      48        20.0     0.0                0             0    245.0  127.5   
3      61        30.0     0.0                0             1    225.0  150.0   
4      46        23.0     0.0                0             0    285.0  130.0   
...   ...         ...     ...              ...           ...      ...    ...   
4233   50         1.0     0.0                0             1    313.0  179.0   
4234   51        43.0     0.0                0             0    207.0  126.5   
4235   48        20.0     0.0                0             0    248.0  131.0   
4236   44        15.0     0.0                0             0    210.0  126.5   
4237   52         0.0     0.0                0             0    269.0  133.5   

      diaBP    BMI  heartRate  glucose  POSSIBILITY OF CVD  
0      70.0  26.97       80.0     77.0                   0  
1      81.0  28.73       95.0     76.0                   0  
2      80.0  25.34       75.0     70.0                   0  
3      95.0  28.58       65.0    103.0                   1  
4      84.0  23.10       85.0     85.0                   0  
...     ...    ...        ...      ...                 ...  
4233   92.0  25.97       66.0     86.0                   1  
4234   80.0  19.71       65.0     68.0                   0  
4235   72.0  22.00       84.0     86.0                   0  
4236   87.0  19.16       86.0     82.0                   0  
4237   83.0  21.47       80.0    107.0                   0  

[4238 rows x 12 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 4238 non-null   int64  
 1   cigsPerDay          4238 non-null   float64
 2   BPMeds              4238 non-null   float64
 3   prevalentStroke     4238 non-null   int64  
 4   prevalentHyp        4238 non-null   int64  
 5   totChol             4238 non-null   float64
 6   sysBP               4238 non-null   float64
 7   diaBP               4238 non-null   float64
 8   BMI                 4238 non-null   float64
 9   heartRate           4238 non-null   float64
 10  glucose             4238 non-null   float64
 11  POSSIBILITY OF CVD  4238 non-null   int64  
dtypes: float64(8), int64(4)
memory usage: 397.4 KB


# Naive Bayes Classifier Implementation

### Step 0: preparing data

In [8]:
# random shuffling of data
#df=df.sample(frac=1)
#display(df)

#not doing this step, as data is already shuffled, as per dataset discription

In [9]:
# taking data , from the DataFrame object, to numpy object
data=df.values
print(data)
print(data.shape)
print(type(data))

[[ 39.   0.   0. ...  80.  77.   0.]
 [ 46.   0.   0. ...  95.  76.   0.]
 [ 48.  20.   0. ...  75.  70.   0.]
 ...
 [ 48.  20.   0. ...  84.  86.   0.]
 [ 44.  15.   0. ...  86.  82.   0.]
 [ 52.   0.   0. ...  80. 107.   0.]]
(4238, 12)
<class 'numpy.ndarray'>


In [10]:
#separating target label, from rest of the attributes
X=data[:,:-1]  
Y=data[:,-1]  # target label
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 39.     0.     0.   ...  26.97  80.    77.  ]
 [ 46.     0.     0.   ...  28.73  95.    76.  ]
 [ 48.    20.     0.   ...  25.34  75.    70.  ]
 ...
 [ 48.    20.     0.   ...  22.    84.    86.  ]
 [ 44.    15.     0.   ...  19.16  86.    82.  ]
 [ 52.     0.     0.   ...  21.47  80.   107.  ]]
(4238, 11)
[0. 0. 0. ... 0. 0. 0.]
(4238,)


### step1 : splitting data for training and testing

In [11]:
#performing split , to train,test data
split=0.7*X.shape[0]
print(split)
split=int(split)
print("split length:",split)
print()

X_train= X[:split,:]
Y_train=Y[:split]
X_test=X[split:,:]
Y_test=Y[split:]

print("X_train:",X_train.shape)
print("X_test:",X_test.shape)
print("Y_train:",Y_train.shape)
print("Y_test:",Y_test.shape)

2966.6
split length: 2966

X_train: (2966, 11)
X_test: (1272, 11)
Y_train: (2966,)
Y_test: (1272,)


### Step 2: NBC implementation 

In [12]:
#with laplace correction
def prior_prob(label,y_train=Y_train):
    totalNumber_TrainingSamples=y_train.shape[0] #2559
    totalNumber_withLabel=np.sum(y_train==label)
    V=len(np.unique(y_train))
    #print(V)
    
    return (totalNumber_withLabel+1)/(totalNumber_TrainingSamples+V)
    

In [13]:
# using the above function
print(prior_prob(0),prior_prob(1))

0.8463611859838275 0.15363881401617252


In [14]:
#implementing with Laplace Correction
def cond_prob(column_index,column_value_inQuery,label,x_train=X_train,y_train=Y_train):
    x_filtered=x_train[y_train==label]
    V=len(np.unique(x_train[:,column_index]))
    numerator=np.sum(x_filtered[:,column_index]==column_value_inQuery)
    denominator=np.sum(y_train==label)
    
    return (numerator+1)/(denominator+V)

In [15]:
def predictLabel(queryRow,x_train=X_train,y_train=Y_train):
    classLabelsWeHave=np.unique(y_train) #[0,1]
    numberOfFeatures=x_train.shape[1] #12
    probalilities=[] #to store probability of all classes
    #calculating posterior probability for each label
    for label in classLabelsWeHave:
        likelihood=1.0
        for f in range(numberOfFeatures):
            conditionalProbability=cond_prob(f,queryRow[f],label)
            likelihood*=conditionalProbability
        prior=prior_prob(label)
        postProb=likelihood*prior
        probalilities.append(postProb)
    #print( probalilities)
    index=np.argmax(probalilities) #returns index of max value, in the list
    prediction=classLabelsWeHave[index]
    return prediction
        
    
    

#### understanding how it works, on 1 sample point

In [19]:
predictLabel(X_test[15])


1.0

In [21]:
print(Y_test[:20])
print(Y_test[15])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
1.0


### Step 3: Testing with "Testing Set"

In [22]:
def findScore(x_test=X_test,y_test=Y_test):
    m=y_test.shape[0] #1097
    l=[]
    count_correctPrediction=0
    for i in range(m):
        predictedLabel=predictLabel(x_test[i])
        l.append((predictedLabel,y_test[i]))
        if(predictedLabel==y_test[i]):
            count_correctPrediction+=1
    print("accuracy %=",count_correctPrediction*100/m)
    df1=pd.DataFrame(data=l,columns=["Predicted Label","Actual Label"])
    display(df1)
        

In [23]:
findScore()

accuracy %= 80.73899371069183


Predicted Label  Actual Label
0                 1.0           0.0
1                 0.0           0.0
2                 0.0           0.0
3                 0.0           0.0
4                 0.0           0.0
...               ...           ...
1267              0.0           1.0
1268              0.0           0.0
1269              0.0           0.0
1270              0.0           0.0
1271              0.0           0.0

[1272 rows x 2 columns]

# implementing NBC using models of sk_learn

In [24]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [25]:
gnb=GaussianNB()
mnb=MultinomialNB()

In [26]:
gnb.fit(X_train,Y_train)
mnb.fit(X_train,Y_train)



MultinomialNB()

In [27]:
#calculating score (or) accuracy
score=gnb.score(X_test,Y_test)
print("accuracy of gaussianNB=",score*100)
score=mnb.score(X_test,Y_test)
print("accuracy of multinomialNB=",score*100)
gnb.score?

accuracy of gaussianNB= 83.09748427672956
accuracy of multinomialNB= 76.72955974842768


# conclusion

### Since some of our important attributes are "continonus valued", thus, the "GAUSSIAN MODEL", gives better result

In [12]:
### Measuring Performance , by Evaluating Parameters

In [28]:
def evaluateParameters(Y_pred,Y_test):
    tp,tn,fp,fn=0,0,0,0
    for i in range(len(Y_test)):
        actual=Y_test[i]
        if(actual==1):
            if(actual==Y_pred[i]):
                tp+=1
            else:
                fn+=1
        else:
            if(actual==Y_pred[i]):
                tn+=1
            else:
                fp+=1
    print("\naccuracy= ",(tp+tn)/(tp+tn+fn+fp))
    print("\nsensitivity= ",tp/(tp+fn))
    print("\nspecificity= ",tn/(fp+tn))
    print("\nPPv= ",tp/(tp+fp))
    print("\nNPV= ",tn/(tn+fn))
    
            
            

In [29]:
Y_pred=gnb.predict(X_test)

In [30]:
evaluateParameters(Y_pred,Y_test)


accuracy=  0.8309748427672956

sensitivity=  0.23809523809523808

specificity=  0.9344413665743305

PPv=  0.3879310344827586

NPV=  0.8754325259515571


# saving trained model, for deploying on web

In [31]:
import pickle

In [32]:
with open('nbc_model.pkl','wb') as f:
    pickle.dump(gnb,f)